### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by amitkumarsingh** [alex030293/mean-boilerplate#1]
When iam trying to npm start it fails ?
Attaching the debug log file.
[npm-debug.log](https://github.com/alex030293/mean-boilerplate/files/1680710/npm-debug.log)

**Comment by alejandromav** [comment]
Hello @amitkumarsingh.

I've just tried to clone the repo, run `npm i` and then `npm start` and everything works fine. I guess this must be some misconfiguration on your local machine. 

Can you run any other node applications?


PS: this is an updated version https://github.com/alex030293/node-ng-starter
